# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
    say-hello:
      # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
        docker:
            - image: cimg/node:13.8.0
        # Add steps to the job
        steps:
            - run: echo hello World!

    print-hello:
        docker:
            - image: cimg/node:13.8.0
        steps:
            - run: echo hello!

    print-world:
        docker:
            - image: cimg/node:13.8.0
        steps:
            - run: echo world!

    save-output:
        docker:
            - image: cimg/node:13.8.0
        steps:
            - run: echo sharing some files hurree > ~/output.txt
            - persist_to_workspace:
                root: ~/
                paths:
                    - output.txt

    print-output:
        docker:
            - image: cimg/node:13.8.0
        steps:
            - attach_workspace:
                at: ~/
            - run: cat ~/output.txt

# Invoke jobs via workflows
workflows:
    workflow-demo:
        jobs:
          - say-hello
          - print-hello:
              requires:
                  - say-hello

          - print-world:
              requires:
                  - print-hello

          - save-output:
              requires:
                  - print-world
          - print-output:
              requires:
                  - save-output

